spring:
  application:
    name: poc_web
  
  # H2 文件数据库配置
  datasource:
    url: jdbc:h2:file:./data/quizdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  # JPA & Hibernate 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console

# 服务器端口配置
server:
  port: 8080

